language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t sidsharm8/ssr-render-server -f ./render-server/Dockerfile.dev ./render-server

script:
  - docker run sidsharm8/ssr-render-server npm run test

after_success:
  - docker build -t sidsharm8/multi-ssr-render-server:1 ./render-server  
  - docker build -t sidsharm8/multi-ssr-api-server:1 -f ./api-server/Dockerfile.dev ./api-server 
  - docker build -t sidsharm8/multi-ssr-nginx-server:1 -f ./nginx/Dockerfile.dev ./nginx
  #login in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push sidsharm8/multi-ssr-render-server:1 
  - docker push sidsharm8/multi-ssr-api-server:1
  - docker push sidsharm8/multi-ssr-nginx-server:1

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: react-ssr
  env: ReactSsr-env
  bucket_name: elasticbeanstalk-us-east-2-630733097423
  bucket_path: react-ssr
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  

