export const OTHER_ORIGINS = [
  'Earth (C-137)',
  'Earth (Replacement Dimension)',
  'Abadango',
  'Signus 5 Expanse',
  'Purge Planet',
  'Venzenulon 7',
  'Bepis 9',
  'Earth (C-500A)',
  "Earth (Evil Rick's Target Dimension)",
  'Nuptia 4',
  'Fantasy World',
  'Bird World',
  'Gromflom Prime',
  "Rick's Battery Microverse",
  'The Menagerie',
  'Earth (K-83)',
  'Hideout Planet',
  'Cronenberg Earth',
  "Unity's Planet",
  "Giant's Town",
  'Earth (Unknown dimension)',
  'Anatomy Park',
  'Earth (J19ζ7)',
  'Roy: A Life Well Lived',
  'Eric Stoltz Mask Earth',
  'Glaagablaaga',
  'Gazorpazorp',
  'Resort Planet',
  'Hamster in Butt World',
  'Earth (Giant Telepathic Spiders Dimension)',
  'Alphabetrium',
  'Earth (5-126)',
  'Krootabulon',
  'Pluto',
  "Zeep Xanflorp's Miniverse",
  "Larva Alien's Planet",
  "Mr. Goldenfold's dream",
  'Earth (K-22)',
  'Mr. Meeseeks Box',
  'Mega Gargantuan Kingdom',
  'Gear World',
  'Earth (D-99)',
  'Earth (D716)',
  'Earth (D716-B)',
  'Earth (D716-C)',
  'Earth (J-22)',
  'Planet Squanch',
  'Detoxifier',
  "Kyle's Teenyverse",
  'Trunk World',
  'Plopstar',
  'Girvonesk',
  "Snuffles' Dream",
  'Interdimensional Cable',
  'Earth (Phone Dimension)',
  'Earth (Pizza Dimension)',
  'Greasy Grandma World',
  'Earth (Chair Dimension)',
  'Testicle Monster Dimension',
  'Árboles Mentirosos',
  'Citadel of Ricks',
  'Earth (Fascist Dimension)',
  'Earth (Fascist Shrimp Dimension)',
  'Earth (Fascist Teddy Bear Dimension)',
  'Earth (Wasp Dimension)',
  'Midland Quasar',
  'Globaflyn',
  'Mount Olympus',
  'Plitzville Montana',
  'Earth (Tusk Dimension)',
  'Gramuflack',
  'Draygon',
  'Snake Planet'
];

export const OTHER_SPECIES = [
  'Alien',
  'Humanoid',
  'unknown',
  'Poopybutthole',
  'Animal',
  'Vampire',
  'Robot',
  'Cronenberg',
  'Disease',
  'Parasite'
];
